export const LOAD_ASSETS = 'LOAD_ASSETS';
export const LOAD_ASSETS_PROGRESS = 'LOAD_ASSETS_PROGRESS';
export const LOAD_ASSETS_LOADED = 'LOAD_ASSETS_LOADED';
export const LOAD_WEBSITE = 'LOAD_WEBSITE';
export const SWITCH_MOBILE = 'SWITCH_MOBILE';
export const SWITCH_CURRENT_PROJECT = 'SWITCH_CURRENT_PROJECT';
export const TRANSITIONING = 'TRANSITIONING';
export const RETURN_HOME = 'RETURN_HOME'
